# Generated by Django 3.1.3 on 2021-02-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='count_violations',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
