# Generated by Django 3.1.3 on 2021-03-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20210207_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='count_violations',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='last_seen_date',
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_date', models.DateTimeField()),
                ('frame', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.statistic')),
            ],
        ),
    ]
