# Generated by Django 3.1.3 on 2021-03-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20210302_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='all_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistic',
            name='last_seen_without_mask',
            field=models.DateTimeField(null=True),
        ),
    ]
