# Generated by Django 3.1.3 on 2021-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_domain',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
