# Generated by Django 3.1.3 on 2021-02-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210204_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='stats',
        ),
        migrations.AddField(
            model_name='statistic',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
