# Generated by Django 3.1.3 on 2021-02-04 17:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210204_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='date',
        ),
        migrations.AddField(
            model_name='statistic',
            name='last_seen_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 17, 38, 14, 55105, tzinfo=utc), null=True),
        ),
    ]
