# Generated by Django 3.1.3 on 2021-02-04 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210204_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='last_seen_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
