# Generated by Django 3.1.3 on 2021-02-05 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210204_1803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
